spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        group: DEV_GROUP
        server-addr: 127.0.0.1:8848
        namespace: DEV
    sentinel:
      transport:
        port: 8720
        dashboard: 127.0.0.1:8000

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true
